DROP TABLE IF EXISTS auth_user_groups CASCADE;
DROP TABLE IF EXISTS auth_group_permissions CASCADE;
DROP TABLE IF EXISTS auth_user_permissions CASCADE;
DROP TABLE IF EXISTS auth_groups CASCADE;
DROP TABLE IF EXISTS auth_permissions CASCADE;
DROP TABLE IF EXISTS auth_otps CASCADE;
DROP TABLE IF EXISTS auth_users CASCADE;
